/* Include Files */

#include "driverlib.h"
#include "device.h"
#include "F021_F28003x_C28x.h"

/* Enum */

typedef enum {
    BFLASH_BANK0_SECTOR0,
    BFLASH_BANK0_SECTOR1,
    BFLASH_BANK0_SECTOR2,
    BFLASH_BANK0_SECTOR3,
    BFLASH_BANK0_SECTOR4,
    BFLASH_BANK0_SECTOR5,
    BFLASH_BANK0_SECTOR6,
    BFLASH_BANK0_SECTOR7,
    BFLASH_BANK0_SECTOR8,
    BFLASH_BANK0_SECTOR9,
    BFLASH_BANK0_SECTOR10,
    BFLASH_BANK0_SECTOR11,
    BFLASH_BANK0_SECTOR12,
    BFLASH_BANK0_SECTOR13,
    BFLASH_BANK0_SECTOR14,
    BFLASH_BANK0_SECTOR15,

    BFLASH_BANK1_SECTOR0,
    BFLASH_BANK1_SECTOR1,
    BFLASH_BANK1_SECTOR2,
    BFLASH_BANK1_SECTOR3,
    BFLASH_BANK1_SECTOR4,
    BFLASH_BANK1_SECTOR5,
    BFLASH_BANK1_SECTOR6,
    BFLASH_BANK1_SECTOR7,
    BFLASH_BANK1_SECTOR8,
    BFLASH_BANK1_SECTOR9,
    BFLASH_BANK1_SECTOR10,
    BFLASH_BANK1_SECTOR11,
    BFLASH_BANK1_SECTOR12,
    BFLASH_BANK1_SECTOR13,
    BFLASH_BANK1_SECTOR14,
    BFLASH_BANK1_SECTOR15,

    BFLASH_BANK2_SECTOR0,
    BFLASH_BANK2_SECTOR1,
    BFLASH_BANK2_SECTOR2,
    BFLASH_BANK2_SECTOR3,
    BFLASH_BANK2_SECTOR4,
    BFLASH_BANK2_SECTOR5,
    BFLASH_BANK2_SECTOR6,
    BFLASH_BANK2_SECTOR7,
    BFLASH_BANK2_SECTOR8,
    BFLASH_BANK2_SECTOR9,
    BFLASH_BANK2_SECTOR10,
    BFLASH_BANK2_SECTOR11,
    BFLASH_BANK2_SECTOR12,
    BFLASH_BANK2_SECTOR13,
    BFLASH_BANK2_SECTOR14,
    BFLASH_BANK2_SECTOR15,

    BFLASH_NUM_SECTORS
} BflashSector_t;

/* Flash Wait states */
#define BFLASH_WAITSTATES (5u)

/* Extern Function */
extern void BFLASH_init(void);
extern void BFLASH_clear(void);
extern void BFLASH_write(void);
